### ISSUE TITLE
E池，矿机名显示错误

### ISSUE THREAD

**Issue by jiangyuhang124** [Char1esOrz/minerProxy#1]
E池通过mp中转后，挖矿地址矿机名显示为default，抽水地址矿机名显示为devfee

**Comment by jiangyuhang124** [comment]
> 

测试版本为win，另外，tg没开

**Comment by why123bs** [comment]
TG是搞错了吧，整一个频道干什么，不应该弄讨论群吗，没发说话。

**Comment by Char1esOrz** [comment]
@jiangyuhang124 刚刚更新的新的版本已经修复了该问题,抽水地址矿机名显示为devfee是没有问题的
@why123bs TG我新创建了一个群组https://t.me/minerProxyGroup

**Comment by Char1esOrz** [comment]
问题已解决
