### ISSUE TITLE
用服务器

### ISSUE THREAD

**Issue by kiloppertry** [Char1esOrz/minerProxy#2]

**Comment by kiloppertry** [comment]
用的btc.com.   用服务器中转了地址为IPXXXX，矿机用的IPXXXX，我根据你的方法在服务器上中转矿池地址用的是官方挖矿地址ip，但是没有抽水成功 ，不知道是什么原因。 mail:  kiloppertry@gmail.com

**Comment by Char1esOrz** [comment]
目前我仅测试了flexpool和ethermine

**Comment by Char1esOrz** [comment]
我刚刚看了下btc.com 他的矿池协议仅支持tcp没有ssl,所以无法使用,我下个版本会更新开放使用tcp,但是我不建议这么做,CN目前使用tcp容易被查水表,更新了我会在这里回复你

**Comment by kiloppertry** [comment]
好的，非常感谢你的答复。请问，鱼池支持ssl吗。
另外我的步骤是对的吗:
假设鱼池可用。
首先在服务器上对鱼池的A地址进行转发到服务器，然后所有矿机用服务器的B地址进行挖矿，
第三步将你的文件创建在服务器上，中转地址也用的A地址，端口用默认的15555，钱包用自己的抽成0. 50.



Sent from my Galaxy



-------- Original message --------
From: Char1esOrz ***@***.***>
Date: 12/3/21 6:45 AM (GMT+08:00)
To: Char1esOrz/minerProxy ***@***.***>
Cc: kiloppertry ***@***.***>, Author ***@***.***>
Subject: Re: [Char1esOrz/minerProxy] 用服务器 (Issue #2)


我刚刚看了下btc.com 他的矿池协议仅支持tcp没有ssl,所以无法使用,我下个版本会更新开放使用tcp,但是我不建议这么做,CN目前使用tcp容易被查水表,更新了我会在这里回复你

―

**Comment by Char1esOrz** [comment]
最新的已经支持tcp了,自行测试
